### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by patricklodder** [DemonRx/Doge-Bootstrap#1]
Hey! Could you please contact me at re: tip payout?

Thx :-)

**Comment by DemonRx** [comment]
Done :)

**Comment by DemonRx** [comment]
@patricklodder what's the status on the tip payouts?

**Comment by DemonRx** [comment]
@patricklodder Hello mate, I'm really at a confusion about what is happening with the reason I was contacted here regarding a tip payout, and to date nothing has come of it. I am respectfully requesting some detail as to why there has been no tip issued out?

If it has been decided for whatever reason that the development team decided not to do this. Then out of professional courteousy please inform me of such decision. 

Otherwise, whatever this was about has me on a bit of an alert being I had provided my personal email in order to make contact with the provided email that was given here...and has since been edited out of the comment, see here: ![Screenshot from 2021-04-25 03-31-08](https://user-images.githubusercontent.com/18432686/115984774-d862a700-a576-11eb-9c1d-1fc04b6c2743.png) 
even so that doesn't delete that email from the history of the comments lol. Then not getting any further responses when I inquired as to why no tips were received after some days went by.

If I get no response. I can try other channels to get to the bottom of this (including github support). Cause at this point i'm concerned of a potential phishing attempt has occurred (acquiring my email). 

I'm just asking for some explanation as to what is going on. Thank you !
